import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-vote-count-table',
  templateUrl: './vote-count-table.component.html',
  styleUrls: ['./vote-count-table.component.css']
})
export class VoteCountTableComponent implements OnInit {

  constructor() {
    setTimeout(() => { this.loadingIndicator = false; }, 1500);
  }

  ngOnInit() {
  }

  rows = [
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },
    {
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },{
      name: 'Austin',
      gender: 'Male',
      gender2: 'Male',
      gender3: 'Male',
      gender4: 'Male',
      gender5: 'Male',
      gender6: 'Male',
      gender7: 'Male',
      gender8: 'Male',
      company: 'Swimlane',
    },


  ];
  columns = [
    { prnameop: 'name' },
    { name: 'Gender' },
    { name: 'Gender2' },
    { name: 'Gender3' },
    { name: 'Gender4' },
    { name: 'Gender5' },
    { name: 'Gender6' },
    { name: 'Gender7' },
    { name: 'Gender8' },
    { name: 'Company' }
  ];
  loadingIndicator: boolean = true;


}
